### ISSUE TITLE
add a column with the current upstream version

### ISSUE THREAD

**Issue by peutch** [air-balloon/debian-dashboard#11]
Hi,

Very nice.
It is reminding me an old attempt on my side (see https://lists.debian.org/debian-qa/2020/02/msg00002.html).
Could it be possible to have a column for the upstream version?  UDD have one stored.

An optionally to introduce a text color style when upstream is greater than the one in Debian?
(what is Standards-version?)
Like for instance in such a table https://udd.debian.org/dmd/?packages%40qa.debian.org#versions
This could help to focus on neglected /abandoned that are also « obsolete ».
I think there is a function added in the UDD pgsql to compare 2 versions in a compliant way.

Finally, it could be also interesting to have column reordering/showing/hiding facilities (maybe using Bootstrap Table component, I used it for my prototype DebiAntiq).

Any way, thanks!

**Comment by peutch** [comment]
For curiosity, this is what DebiAntiq looks like:
![Capture d’écran du 2023-03-17 20-03-13](https://user-images.githubusercontent.com/3142330/225995836-55781a3c-0798-4996-8816-8529abacd8f2.png)

**Comment by williamdes** [comment]
Hi @peutch 👋🏻 
Debian is out of freeze, let's restart Debian packaging !

> For curiosity, this is what DebiAntiq looks like:

Can you give me a link to it ? or was it a project that was not online ?

> (what is Standards-version?)

It's the Debian standards version: https://www.debian.org/doc/debian-policy/upgrading-checklist.html#version-4-6-2


Thank you for your input on the versions, I will definitely have a look some time this year

**Comment by williamdes** [comment]
I moved this repo to https://salsa.debian.org/williamdes/debian-dashboard
